# nginx:
#   build: ./nginx
#   links:
#     - pawix_web:pawix_web
#   ports:
#     - 80:80
db:
  image: postgres
  ports:
    - "5432"
pawix_api:
  build: ./api
  command: bundle exec rackup -o 0.0.0.0 -p 9292
  volumes:
    - ./api:/api
  links:
    - db
pawix_bot:
  build: ./bot
  command: ruby app.rb
  volumes:
    - ./bot:/bot
  env_file: .env
  links:
   - pawix_api
