nginx:
  build: ./nginx
  links:
    - api:api
  ports:
    - 80:80
db:
  image: postgres
  ports:
    - "5432"
api:
  build: ./api
  command: bundle exec rackup -o 0.0.0.0 -p 9292
  volumes:
    - ./api:/api
  links:
    - db
bot:
  build: ./bot
  command: ruby app.rb
  volumes:
    - ./bot:/bot
  env_file: .env
  links:
   - api
