connection: &connection
  adapter: postgresql
  min_messages: WARNING
  encoding: unicode
  pool: 5
  username: postgres
  password:
  host: db

development:
  <<: *connection
  database: pawix_development

test: &test
  <<: *connection
  database: pawix_test

production:
  <<: *connection
  database: pawix_production
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
